apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "filter.fullname" . }}-config
data:
  config.ini: |-
    [{{ .Values.deviceName | default "default" }}]
    source = {{ .Values.deviceSource | default 0 }}
