apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "filter.fullname" . }}-config
data:
  config.ini: |-
    [device0]
    name = {{ .Values.deviceName | default "webcam" }}
    source = {{ .Values.deviceSource | default 0 }}
