apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nanomq.fullname" . }}-config
data:
  nanomq.conf: |-
    mqtt = {
      max_packet_size = 260MB
      max_mqueue_len = 20000000      
      retry_interval = 10s
      keepalive_multiplier = 1.25 
      property_size = 32          
    }

    listeners.tcp {
        bind = "0.0.0.0:1883"
    }    

    listeners.ws {
        bind = "0.0.0.0:8083/mqtt"
    }

    http_server {
        port = 8081
        limit_conn = 6
        username = admin
        password = public
        auth_type = basic
        jwt {
            public.keyfile = "/etc/certs/jwt/jwtRS256.key.pub"
        }
    }    


    log {
        to = [console]
        level = debug
    }

    auth {
        allow_anonymous = true
        no_match = allow
        deny_action = ignore
        
        cache = {
            max_size = 32
            ttl = 1m
        }
        
        # password = {include "/etc/nanomq_pwd.conf"}
        # acl = {include "/etc/nanomq_acl.conf"}
    }    