apiVersion: v1
kind: Service
metadata:
  name: {{ include "nanomq.fullname" . }}
  labels:
    {{- include "nanomq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: broker
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http  
  selector:
    {{- include "nanomq.selectorLabels" . | nindent 4 }}
